<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="signin2.css" rel="stylesheet">
</head>

<body class="text-center">
<form ACTION="aplikacja" METHOD="GET" class="form-signin">
    <img class="mb-4" src="dontMess.gif" alt="" >
    <h1 class="h3 mb-3 font-weight-normal">Don't mess with my application</h1>
    <h1 class="h3 mb-3 font-weight-normal">Value was incorrect</h1>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Back</button>
</form>
</body>
</html>